version: '3.8'

services:
  postgres:
    container_name: app_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - custom_network
    restart: unless-stopped
  
  minio:
    image: 'bitnami/minio:latest'
    container_name: app_storage
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_admin
    networks:
      - custom_network

volumes: 
  postgres:

networks:
  custom_network:
    driver: bridge
